global:
  scrape_interval: 15s  

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Spring Boot application's actuator metrics
  - job_name: 'movie-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movie-service:8080']

  - job_name: 'recommendation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recommendation-service:8080']

  # Scrape PostgreSQL exporter metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
